---
- name: Update g1 server
  hosts: g1
  become: yes
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: present
    when: ansible_distribution == "ec2-user"

  - name: start httpd
    service:
      name: httpd
      state: started
    when: ansible_distribution == "ec2-user"

  - name: enable httpd
    service:
      name: httpd
      enabled: yes
    when: ansible_distribution == "ec2-user"


  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: start apache2
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"
  
  - name: enable apache2
    service:
      name: apache2
      enabled: yes
    when: ansible_distribution == "Ubuntu"
...
